#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Genezzo
version:      0.25
version_from: lib/Genezzo/GenDBI.pm
installdirs:  site
requires:
    IO::Handle:                    0.0
    File::Path:                    0.0
    IO::File:                      0.0
    File::Spec:                    0.0
    Term::ReadLine:                0.0
    Text::ParseWords:              0.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
