# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Genezzo
version:      0.58
version_from: lib/Genezzo/GenDBI.pm
installdirs:  site
requires:
    File::Path:                    0.0
    File::Spec:                    0.0
    IO::Handle:                    0.0
    Parse::RecDescent:             1.94
    Term::ReadLine:                0.0
    Text::ParseWords:              0.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
license: gpl
abstract: an extensible database system (with SQL and DBI)
author: Jeffrey I Cohen (jcohen@cpan.org)
